blank_issues_enabled: true
contact_links:
  - name: iPipeline Terraform Module Code of Conduct
    url: CODE_OF_CONDUCT.md
    about: If this is your first time here, please take a moment to read the iPipeline Terraform Module Code of Conduct.
