name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
#    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master
#    paths-ignore:
#      - '.github/**'

# based on https://learn.hashicorp.com/tutorials/terraform/github-actions

env:
  tf_working_dir: '/applied/accounts/.'
  tf_version: 'latest'
  tg_version: 'latest'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
#        working-directory: './modules/iam'
        working-directory: ${{ env.tf_working_dir }}

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      # - name: Install Terraform and Terragrunt
      #   run: |
      #     brew tap rocketinsights/tgenv
      #     brew install tfenv tgenv
      #     tfenv install latest
      #     tgenv install latest
      # - name: Get Versions
      #   run: |
      #     terragrunt --version
      #     terraform --version

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::940407795328:role/github_orchestration_role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: ${{ env.tf_version }}

      # installing Terragrunt this way takes longer, but at the time there wasn't a setup-terragrunt re-usable action
      - name: Install Terragrunt
        run: |
          brew tap rocketinsights/tgenv
          brew install tgenv
          tgenv install ${{ env.tg_version }}

      - name: Get Versions
        run: |
          terragrunt --version
          terraform --version

      - run: ls 
