name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
#    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master
#    paths-ignore:
#      - '.github/**'

# based on https://learn.hashicorp.com/tutorials/terraform/github-actions

env:
  tf_working_dir: './applied/accounts/'
  tf_version: 'latest'
  tg_version: 'latest'
  orchestration_role_arn: 'arn:aws:iam::940407795328:role/github_orchestration_role'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.tf_working_dir }}

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.orchestration_role_arn }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: ${{ env.tg_version }}

      - name: Get Versions
        run: |
          terragrunt --version
          terraform --version

      - name: Validate & Test Code
        run: |
          terragrunt run-all init --terragrunt-non-interactive
          terragrunt run-all validate --terragrunt-non-interactive

      - run: echo ${{ github.event }}
      - name: Plan
        if: github.event_name == 'pull_request'
        run: |
          terragrunt run-all plan --terragrunt-non-interactive

      - name: Apply
        if: github.event_name == 'push'
        run: |
          terragrunt run-all apply --terragrunt-non-interactive
