name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master      
    paths-ignore:
      - '.github/**'

env:
  tf_working_dir: '/applied/accounts/.'
  tf_version: '1.1.0'
  tg_version: '0.35.13'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::940407795328:role/github_orchestration_role

      - name: 'Terraform Setup'
        uses: autero1/action-terraform@v1.0.3
        with:
          terraform_version: ${{ env.tf_version }}
 
      - name: 'Terragrunt Setup'
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: ${{ env.tg_version }}
      
      - name: 'Terragrunt Init'
        run: terragrunt run-all init --terragrunt-noninteractive

      - name: 'Terragrunt Validate'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: "terragrunt run-all --terragrunt-non-interactive"
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true

      - name: 'Terragrunt Plan'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: "terragrunt run-all --terragrunt-non-interactive"
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
          
      - name: 'Terragrunt Apply'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: "terragrunt run-all --terragrunt-non-interactive"
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true          
